export const mockTimeline = {
  timeline_id: 1,
  ticker: 'SPX',
  interval: '5min',
  created_at: '2022-12-13 09:30:00.810302+00',
  date: '2022-12-13',
  start_time: '9:30AM',
  start_price: 3730,
  end_price: 3670,
  bsp: 60,
  cards: [
    {
      card_id: 1,
      created_at: '2022-12-13 09:30:00.810302+00',
      alerts: [
        {
          alert_id: 10,
          current_price: 3670,
          current_time: '10:15AM',
          ema13: 3669,
          ema63: 3674,
          ema_difference: 5,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'GET OUT NOW!!!',
        },
        {
          alert_id: 9,
          current_price: 3680,
          current_time: '10:10AM',
          ema13: 3685,
          ema63: 3699,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 8,
          current_price: 3691,
          current_time: '10:05AM',
          ema13: 3689,
          ema63: 3699,
          ema_difference: 7,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'BE CAUTIOUS! Is your STOP LIMIT in place?',
        },
        {
          alert_id: 7,
          current_price: 3705,
          current_time: '10:00AM',
          ema13: 3709,
          ema63: 3723,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 6,
          current_price: 3714,
          current_time: '9:55AM',
          ema13: 3712,
          ema63: 3723,
          ema_difference: 12,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 5,
          current_price: 3719,
          current_time: '9:50AM',
          ema13: 3714,
          ema63: 3724,
          ema_difference: 10,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 4,
          current_price: 3740,
          current_time: '9:45AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 1.5,
          bps: null,
          cross: false,
          cross_eta: '9:35AM',
          cross_time: '9:45AM',
          trend: 'bullish',
          stoplight_message: 'NEW TREND ACTIVATED',
        },
        {
          alert_id: 3,
          current_price: 3725,
          current_time: '9:40AM',
          ema13: 3727,
          ema63: 3724,
          ema_difference: null,
          rate_of_change: 1.0,
          bps: 3,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 2,
          current_price: 3728,
          current_time: '9:35AM',
          ema13: 3731,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 0.5,
          bps: 6,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 1,
          current_price: 3740,
          current_time: '9:30AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: null,
          bps: 12,
          cross: false,
          cross_eta: null,
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
      ],
    },
    {
      card_id: 2,
      created_at: '2022-12-13 09:30:00.810302+00',
      alerts: [
        {
          alert_id: 10,
          current_price: 3670,
          current_time: '10:15AM',
          ema13: 3669,
          ema63: 3674,
          ema_difference: 5,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'GET OUT NOW!!!',
        },
        {
          alert_id: 9,
          current_price: 3680,
          current_time: '10:10AM',
          ema13: 3685,
          ema63: 3699,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 8,
          current_price: 3691,
          current_time: '10:05AM',
          ema13: 3689,
          ema63: 3699,
          ema_difference: 7,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'BE CAUTIOUS! Is your STOP LIMIT in place?',
        },
        {
          alert_id: 7,
          current_price: 3705,
          current_time: '10:00AM',
          ema13: 3709,
          ema63: 3723,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 6,
          current_price: 3714,
          current_time: '9:55AM',
          ema13: 3712,
          ema63: 3723,
          ema_difference: 12,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 5,
          current_price: 3719,
          current_time: '9:50AM',
          ema13: 3714,
          ema63: 3724,
          ema_difference: 10,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 4,
          current_price: 3740,
          current_time: '9:45AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 1.5,
          bps: null,
          cross: false,
          cross_eta: '9:35AM',
          cross_time: '9:45AM',
          trend: 'bullish',
          stoplight_message: 'NEW TREND ACTIVATED',
        },
        {
          alert_id: 3,
          current_price: 3725,
          current_time: '9:40AM',
          ema13: 3727,
          ema63: 3724,
          ema_difference: null,
          rate_of_change: 1,
          bps: 3,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 2,
          current_price: 3728,
          current_time: '9:35AM',
          ema13: 3731,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 0.5,
          bps: 6,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 1,
          current_price: 3740,
          current_time: '9:30AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: null,
          bps: 12,
          cross: false,
          cross_eta: null,
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
      ],
    },
    {
      card_id: 3,
      created_at: '2022-12-13 09:30:00.810302+00',
      alerts: [
        {
          alert_id: 10,
          current_price: 3670,
          current_time: '10:15AM',
          ema13: 3669,
          ema63: 3674,
          ema_difference: 5,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'GET OUT NOW!!!',
        },
        {
          alert_id: 9,
          current_price: 3680,
          current_time: '10:10AM',
          ema13: 3685,
          ema63: 3699,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 8,
          current_price: 3691,
          current_time: '10:05AM',
          ema13: 3689,
          ema63: 3699,
          ema_difference: 7,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'BE CAUTIOUS! Is your STOP LIMIT in place?',
        },
        {
          alert_id: 7,
          current_price: 3705,
          current_time: '10:00AM',
          ema13: 3709,
          ema63: 3723,
          ema_difference: 14,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 6,
          current_price: 3714,
          current_time: '9:55AM',
          ema13: 3712,
          ema63: 3723,
          ema_difference: 12,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 5,
          current_price: 3719,
          current_time: '9:50AM',
          ema13: 3714,
          ema63: 3724,
          ema_difference: 10,
          rate_of_change: null,
          bps: null,
          cross: true,
          cross_eta: null,
          cross_time: null,
          trend: null,
          stoplight_message: 'TREND looking good!',
        },
        {
          alert_id: 4,
          current_price: 3740,
          current_time: '9:45AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 1.5,
          bps: null,
          cross: false,
          cross_eta: '9:35AM',
          cross_time: '9:45AM',
          trend: 'bullish',
          stoplight_message: 'NEW TREND ACTIVATED',
        },
        {
          alert_id: 3,
          current_price: 3725,
          current_time: '9:40AM',
          ema13: 3727,
          ema63: 3724,
          ema_difference: null,
          rate_of_change: 1,
          bps: 3,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 2,
          current_price: 3728,
          current_time: '9:35AM',
          ema13: 3731,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: 0.5,
          bps: 6,
          cross: false,
          cross_eta: '9:45AM',
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
        {
          alert_id: 1,
          current_price: 3740,
          current_time: '9:30AM',
          ema13: 3735,
          ema63: 3725,
          ema_difference: null,
          rate_of_change: null,
          bps: 12,
          cross: false,
          cross_eta: null,
          cross_time: null,
          trend: 'bullish',
          stoplight_message: '',
        },
      ],
    },
  ],
};